import { ApiProperty } from '@nestjs/swagger';

export class DashboardKpisDto {
  @ApiProperty({
    description: 'Sum of order totals in the window.',
    example: 125000.5,
  })
  totalSales: number;

  @ApiProperty({
    description:
      'Distinct customers who placed a qualifying order in the window.',
    example: 87,
  })
  totalClients: number;

  @ApiProperty({
    description:
      'Average ticket (totalSales / orderCount). 0 when there are no orders.',
    example: 431.03,
  })
  averageTicket: number;

  @ApiProperty({
    description: 'Number of qualifying orders in the window.',
    example: 290,
  })
  orderCount: number;
}

export class MonthlySalesPointDto {
  @ApiProperty({ description: 'Month label.', example: 'January' })
  label: string;

  @ApiProperty({
    description: 'Month number, 1 (Jan) to 12 (Dec).',
    example: 1,
  })
  month: number;

  @ApiProperty({ description: 'Total sales for the month.', example: 10450.9 })
  total: number;
}

export class CategorySliceDto {
  @ApiProperty({
    description: 'Category name, or "Other" for the collapsed tail.',
    example: 'Electronics',
  })
  label: string;

  @ApiProperty({
    description: 'Revenue attributed to this slice.',
    example: 50000,
  })
  amount: number;

  @ApiProperty({
    description: 'Share of total category revenue, 0-100.',
    example: 42.5,
  })
  percentage: number;
}

export class TopProductDto {
  @ApiProperty({ description: 'Product UUID.', format: 'uuid' })
  productId: string;

  @ApiProperty({ description: 'Product name.', example: 'iPhone 15' })
  name: string;

  @ApiProperty({
    description: 'Owning category name, or "Uncategorized".',
    example: 'Electronics',
  })
  category: string;

  @ApiProperty({
    description: 'Revenue generated by this product.',
    example: 19998,
  })
  amount: number;
}

export class RegionSliceDto {
  @ApiProperty({ description: 'Brazilian state UF code.', example: 'SP' })
  state: string;

  @ApiProperty({
    description: 'Revenue from customers in this state.',
    example: 60000,
  })
  amount: number;

  @ApiProperty({
    description: 'Share of total regional revenue, 0-100.',
    example: 35.1,
  })
  percentage: number;
}

export class DashboardOverviewResponseDto {
  @ApiProperty({
    description: 'Headline metrics for the selected window.',
    type: DashboardKpisDto,
  })
  kpis: DashboardKpisDto;

  @ApiProperty({
    description:
      'Sales per month for the current calendar year, January to December (always full year).',
    type: [MonthlySalesPointDto],
  })
  monthlySales: MonthlySalesPointDto[];

  @ApiProperty({
    description:
      'Top 5 categories by revenue plus an "Other" slice for the remainder.',
    type: [CategorySliceDto],
  })
  categories: CategorySliceDto[];

  @ApiProperty({
    description: 'Top 5 products by revenue.',
    type: [TopProductDto],
  })
  topProducts: TopProductDto[];

  @ApiProperty({
    description:
      'Top 5 regions (customer state) by revenue, with percentage share.',
    type: [RegionSliceDto],
  })
  topRegions: RegionSliceDto[];
}
